<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
        <PublishTrimmed>true</PublishTrimmed>
        <GenerateProgramFile>false</GenerateProgramFile>
        
        <UseAppHost>true</UseAppHost> <!--See https://github.com/dotnet/runtime/issues/3704 -->
        <TrimMode>partial</TrimMode>
        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>

    </PropertyGroup>

    <PropertyGroup>
      <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>
    <PropertyGroup>
      <PublishSingleFile>true</PublishSingleFile>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugType>none</DebugType>
    </PropertyGroup>



    <ItemGroup>
        <ProjectReference Include="..\Frontend\Frontend.fsproj" />
        <ProjectReference Include="..\LabsCore\LabsCore.fsproj" />
        <ProjectReference Include="..\LabsParser\LabsParser.fsproj" />
    </ItemGroup>
    
    <ItemGroup>
        <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Argu" Version="6.2.5" />
      <PackageReference Update="FSharp.Core" Version="10.1.201" />
      <PackageReference Include="Scriban" Version="7.2.5" />
    </ItemGroup>


    <ItemGroup>
        <Compile Include="Liquid.fs" />
        <Compile Include="TranslationKit.fs" />
        <Compile Include="ArgParse.fs" />
        <Compile Include="Encode.fs" />
        <Compile Include="Json.fs" />
        <Content Include="templates\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Compile Include="Program.fs" />
    </ItemGroup>
    
</Project>
