module LabsCore.Tokens

// Operators
let tCHOICE = "++"
let tCOMMENT = "#"
let tDIV = "/"
let tGUARD = "->"
let tFATGUARD = "=>"
let tMINUS = "-"
let tMOD = "%"
let tMUL = "*"
let tNEG = "!"
let tPAR = "||"
let tPLUS = "+"
let tRAW = "$"
let tROUNDDIV = ":"
let tSEQ = ";"

// Keywords

let tABS = "abs"
let tCONJ = "and"
let tDISJ = "or"
let tELSE = "else"
let tFALSE = "false"
let tID = "id"
let tIF = "if"
let tMAX = "max"
let tMIN = "min"
let tOF = "of"
let tPICK = "pick"
let tSKIP = "Skip"
let tTHEN = "then"
let tTRUE = "true"
let tUNDEF = "undef"
let tWHERE = "where"